const dummyData = [
  {
    username: "patient1",
    name: "John Smith",
    email: "john.smith@example.com",
    password: "password123",
    dateOfBirth: new Date("1990-05-15"),
    gender: "Male",
    mobileNumber: "1234567890",
    emergencyFullName: "Sarah Smith",
    emergencyMobileNumber: "9876543210",
    emergencyRelation: "Spouse",
  },
  {
    username: "patient2",
    name: "Mary Johnson",
    email: "mary.johnson@example.com",
    password: "pass987",
    dateOfBirth: new Date("1988-07-28"),
    gender: "Female",
    mobileNumber: "9876543210",
    emergencyFullName: "David Johnson",
    emergencyMobileNumber: "1234567890",
    emergencyRelation: "Parent",
  },
  {
    username: "patient3",
    name: "Michael Davis",
    email: "michael.davis@example.com",
    password: "securepass",
    dateOfBirth: new Date("1992-12-03"),
    gender: "Male",
    mobileNumber: "5555555555",
    emergencyFullName: "Emily Davis",
    emergencyMobileNumber: "5555555556",
    emergencyRelation: "Sibling",
  },
  {
    username: "patient4",
    name: "Emily Wilson",
    email: "emily.wilson@example.com",
    password: "password321",
    dateOfBirth: new Date("1995-02-19"),
    gender: "Female",
    mobileNumber: "3333333333",
    emergencyFullName: "Ryan Wilson",
    emergencyMobileNumber: "3333333334",
    emergencyRelation: "Friend",
  },
  {
    username: "patient5",
    name: "Andrew Clark",
    email: "andrew.clark@example.com",
    password: "pass456",
    dateOfBirth: new Date("1987-09-02"),
    gender: "Male",
    mobileNumber: "7777777777",
    emergencyFullName: "Samantha Clark",
    emergencyMobileNumber: "7777777778",
    emergencyRelation: "Spouse",
  },
  {
    username: "patient6",
    name: "Laura Adams",
    email: "laura.adams@example.com",
    password: "laura123",
    dateOfBirth: new Date("1984-08-21"),
    gender: "Female",
    mobileNumber: "8888888888",
    emergencyFullName: "Matthew Adams",
    emergencyMobileNumber: "8888888889",
    emergencyRelation: "Sibling",
  },
  {
    username: "patient7",
    name: "Alex Turner",
    email: "alex.turner@example.com",
    password: "alexpass",
    dateOfBirth: new Date("1991-04-14"),
    gender: "Male",
    mobileNumber: "9999999999",
    emergencyFullName: "Olivia Turner",
    emergencyMobileNumber: "9999999998",
    emergencyRelation: "Spouse",
  },
  {
    username: "patient8",
    name: "Sophia Brown",
    email: "sophia.brown@example.com",
    password: "sophiapass",
    dateOfBirth: new Date("1989-11-07"),
    gender: "Female",
    mobileNumber: "1111111111",
    emergencyFullName: "James Brown",
    emergencyMobileNumber: "1111111112",
    emergencyRelation: "Parent",
  },
  {
    username: "patient9",
    name: "Daniel Taylor",
    email: "daniel.taylor@example.com",
    password: "pass789",
    dateOfBirth: new Date("1993-09-23"),
    gender: "Male",
    mobileNumber: "2222222222",
    emergencyFullName: "Rebecca Taylor",
    emergencyMobileNumber: "2222222223",
    emergencyRelation: "Spouse",
  },
  {
    username: "patient10",
    name: "Olivia White",
    email: "olivia.white@example.com",
    password: "password987",
    dateOfBirth: new Date("1986-03-05"),
    gender: "Female",
    mobileNumber: "4444444444",
    emergencyFullName: "Brian White",
    emergencyMobileNumber: "4444444445",
    emergencyRelation: "Sibling",
  },
];

module.exports = dummyData;
