const dummyData = [
  {
    username: "inactive1",
    name: "Dr. Mark Johnson",
    email: "mark.johnson@example.com",
    password: "inactivepass1",
    dateOfBirth: new Date("1975-06-10"),
    hourlyRate: 30.0,
    affiliation: "General Hospital",
    education: "Doctor of Pharmacy (PharmD)",
    state: "Inactive",
  },
  {
    username: "inactive2",
    name: "Dr. Lisa Williams",
    email: "lisa.williams@example.com",
    password: "inactivepass2",
    dateOfBirth: new Date("1980-08-25"),
    hourlyRate: 29.0,
    affiliation: "City Medical Center",
    education: "Doctor of Pharmacy (PharmD)",
    state: "Inactive",
  },
  {
    username: "inactive3",
    name: "Dr. Richard Davis",
    email: "richard.davis@example.com",
    password: "inactivepass3",
    dateOfBirth: new Date("1978-12-15"),
    hourlyRate: 28.0,
    affiliation: "Community Pharmacy Group",
    education: "Doctor of Pharmacy (PharmD)",
    state: "Inactive",
  },
  {
    username: "inactive4",
    name: "Dr. Karen Smith",
    email: "karen.smith@example.com",
    password: "inactivepass4",
    dateOfBirth: new Date("1983-04-19"),
    hourlyRate: 31.0,
    affiliation: "Sunset Medical Center",
    education: "Doctor of Pharmacy (PharmD)",
    state: "Inactive",
  },
  {
    username: "inactive5",
    name: "Dr. Michael Brown",
    email: "michael.brown@example.com",
    password: "inactivepass5",
    dateOfBirth: new Date("1986-09-05"),
    hourlyRate: 32.0,
    affiliation: "Greenwood Pharmacy",
    education: "Doctor of Pharmacy (PharmD)",
    state: "Inactive",
  },
  {
    username: "pharmacist1",
    name: "John Doe",
    email: "john.doe@example.com",
    password: "password123",
    dateOfBirth: new Date("1985-10-15"),
    hourlyRate: 35.0,
    affiliation: "Community Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist2",
    name: "Alice Smith",
    email: "alice.smith@example.com",
    password: "pass987",
    dateOfBirth: new Date("1990-06-28"),
    hourlyRate: 40.0,
    affiliation: "Hospital Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist3",
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    password: "securepass",
    dateOfBirth: new Date("1988-12-03"),
    hourlyRate: 32.5,
    affiliation: "Independent Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist4",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    password: "password321",
    dateOfBirth: new Date("1992-07-19"),
    hourlyRate: 37.0,
    affiliation: "Clinical Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist5",
    name: "Michael Lee",
    email: "michael.lee@example.com",
    password: "pass456",
    dateOfBirth: new Date("1983-05-02"),
    hourlyRate: 38.5,
    affiliation: "Retail Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist6",
    name: "Laura Adams",
    email: "laura.adams@example.com",
    password: "laura123",
    dateOfBirth: new Date("1987-08-21"),
    hourlyRate: 36.0,
    affiliation: "Community Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist7",
    name: "Brian Wilson",
    email: "brian.wilson@example.com",
    password: "brianpass",
    dateOfBirth: new Date("1991-04-14"),
    hourlyRate: 39.0,
    affiliation: "Hospital Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist8",
    name: "Sarah Brown",
    email: "sarah.brown@example.com",
    password: "sarahpass",
    dateOfBirth: new Date("1989-11-07"),
    hourlyRate: 34.0,
    affiliation: "Independent Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist9",
    name: "Daniel Clark",
    email: "daniel.clark@example.com",
    password: "pass789",
    dateOfBirth: new Date("1984-09-23"),
    hourlyRate: 37.5,
    affiliation: "Clinical Pharmacy",
    education: "PharmD",
    state: "Active",
  },
  {
    username: "pharmacist10",
    name: "Olivia Turner",
    email: "olivia.turner@example.com",
    password: "password987",
    dateOfBirth: new Date("1993-03-05"),
    hourlyRate: 35.5,
    affiliation: "Retail Pharmacy",
    education: "PharmD",
    state: "Active",
  },
];

module.exports = dummyData;
